//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A4BusService.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SPTranslations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SPTranslations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("A4BusService.App_GlobalResources.SPTranslations", typeof(SPTranslations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string backToList {
            get {
                return ResourceManager.GetString("backToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus Routes.
        /// </summary>
        public static string BusRoutes {
            get {
                return ResourceManager.GetString("BusRoutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus Stops.
        /// </summary>
        public static string BusStops {
            get {
                return ResourceManager.GetString("BusStops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        public static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City .
        /// </summary>
        public static string city {
            get {
                return ResourceManager.GetString("city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Driver Record.
        /// </summary>
        public static string CreateTitle {
            get {
                return ResourceManager.GetString("CreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Hired .
        /// </summary>
        public static string dateHired {
            get {
                return ResourceManager.GetString("dateHired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver.
        /// </summary>
        public static string Driver {
            get {
                return ResourceManager.GetString("Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drivers.
        /// </summary>
        public static string Drivers {
            get {
                return ResourceManager.GetString("Drivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to field {0} must be a date.
        /// </summary>
        public static string FieldMustBeDate {
            get {
                return ResourceManager.GetString("FieldMustBeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to field {0} must be a number.
        /// </summary>
        public static string FieldMustBeNumeric {
            get {
                return ResourceManager.GetString("FieldMustBeNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name .
        /// </summary>
        public static string firstName {
            get {
                return ResourceManager.GetString("firstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string fullName {
            get {
                return ResourceManager.GetString("fullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Phone .
        /// </summary>
        public static string homePhone {
            get {
                return ResourceManager.GetString("homePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name .
        /// </summary>
        public static string lastName {
            get {
                return ResourceManager.GetString("lastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal .
        /// </summary>
        public static string postalCode {
            get {
                return ResourceManager.GetString("postalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid value for {1}.
        /// </summary>
        public static string PropertyValueInvalid {
            get {
                return ResourceManager.GetString("PropertyValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a value is required for {0}.
        /// </summary>
        public static string PropertyValueRequired {
            get {
                return ResourceManager.GetString("PropertyValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province Code.
        /// </summary>
        public static string provinceCode {
            get {
                return ResourceManager.GetString("provinceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be empty or just spaces.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to section 2.
        /// </summary>
        public static string Section {
            get {
                return ResourceManager.GetString("Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Address .
        /// </summary>
        public static string street {
            get {
                return ResourceManager.GetString("street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sam&apos;s Bus Service.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Phone .
        /// </summary>
        public static string workPhone {
            get {
                return ResourceManager.GetString("workPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not on file.
        /// </summary>
        public static string XNotOnFile {
            get {
                return ResourceManager.GetString("XNotOnFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} record created : .
        /// </summary>
        public static string XRecordCreated {
            get {
                return ResourceManager.GetString("XRecordCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exception trying to create new {0}:.
        /// </summary>
        public static string XRecordCreatingException {
            get {
                return ResourceManager.GetString("XRecordCreatingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} record created : .
        /// </summary>
        public static string XRecordDeleted {
            get {
                return ResourceManager.GetString("XRecordDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exception trying to delete {0}:.
        /// </summary>
        public static string XRecordDeletingException {
            get {
                return ResourceManager.GetString("XRecordDeletingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} record edited : .
        /// </summary>
        public static string XRecordEdited {
            get {
                return ResourceManager.GetString("XRecordEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exception trying to edit {0}:.
        /// </summary>
        public static string XRecordEditingException {
            get {
                return ResourceManager.GetString("XRecordEditingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to finding {0} threw and exception.
        /// </summary>
        public static string XRecordFindingException {
            get {
                return ResourceManager.GetString("XRecordFindingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should have 10 digits.
        /// </summary>
        public static string XShold10Digits {
            get {
                return ResourceManager.GetString("XShold10Digits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be two letters.
        /// </summary>
        public static string XShould2Letters {
            get {
                return ResourceManager.GetString("XShould2Letters", resourceCulture);
            }
        }
    }
}
